version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mathjax
    versions:
    - 3.1.3
  - dependency-name: addons-linter
    versions:
    - 2.19.0
    - 3.0.0
    - 3.2.0
  - dependency-name: sinon
    versions:
    - 10.0.1
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
  - dependency-name: chai
    versions:
    - 4.3.1
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.4
  - dependency-name: bulma
    versions:
    - 0.9.2
