language: node_js

node_js:
- 'lts/*'

dist: trusty

sudo: false

addons:
  chrome: stable # have Travis install chrome stable.

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
- export PATH=$HOME/.yarn/bin:$PATH

script:
- npm run lint
- npm run build
- npm run test
