= Contributing
:uri-nodejs: http://nodejs.org
:uri-nvm: https://github.com/creationix/nvm
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This guide will give you all the necessary information you need to become a successful code contributor!

== Setup

To build this project, you will need {uri-nodejs}[Node] and `npm`.
The best way to install Node is to use {uri-nvm}[nvm] (Node Version Manager).

We recommend using the latest long term support (LTS) release of Node. While you can use other versions of Node, this extension is only tested against active LTS releases.

NOTE: If you feel more comfortable with `yarn`, you can use it as an alternative to `npm`

== Building

. Install all the dependencies
+
 $ npm install

. Build the project 
+
 $ npm run build
+
This command will produce a zip file that can be load in Chrome: [.path]_dist/asciidoctor-browser-extension.zip_

. Run tests
+
 $ npm run test
+
--
*Testing notes*

The tests suite is run against an Headless instance of Chromium::
When you installed the development dependencies, https://github.com/GoogleChrome/puppeteer[Puppeteer] had automatically installed Chromium for your platform.
So you shouldn't need to manually install Chromium or Chrome in order to run the tests suite.

It is not recommended to run the test suite as `root`::
If you're as `root`, you'll see the following error in the console:
+
....
INFO [launcher]: Starting browser ChromeHeadless
ERROR [launcher]: Cannot start ChromeHeadless
	ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
....
+
To work around this issue you can run the following command instead:

 $ npm run test:nosandbox
+
It will launch a Chromium instance with the `--no-sandbox` argument.
--

. Check your code against the code rules.
  This project is using a code linter to enforce code consistency. 
  To make sure that the code you have contributed follows the code rules, execute the following command:

 $ npm run lint:code

== Safari

The Safari app extension lives in [.path]_safari/_ as a thin Xcode project: it references the files in [.path]_app/_ directly (no copy), so [.path]_app/_ remains the single source of truth for the extension's code and assets, shared with the Chrome/Firefox builds.

. Build the web extension assets first
+
 $ npm run build

. Build the Safari app (requires Xcode and macOS)
+
 $ npm run build:safari
+
Or open the project in Xcode with `npm run open:safari` to run/debug it directly.

NOTE: Archiving and submitting to the Mac App Store is currently done manually from Xcode's Organizer (Product > Archive > Distribute App), since it requires interactively selecting your Apple Developer team, provisioning, and validating the submission.

== Add-on Linter

Mozilla provides a Node.js package to validate an add-on.
You can run the linter with `npm`:

 $ npm run lint:firefox

NOTE: The linter will inspect the archive produced by `npm run build`, so make sure the file `dist/asciidoctor-browser-extension.zip` is present before running this command.

== Release
Follow these steps to make a release.

. Build and run the tests
. Make sure that everything is working fine by loading the extension as an "unpack extension"
. Edit the `changelog.adoc` file
. Update the version in `app/manifest.json`
. Commit the changes
. Tag the version
. Connect to the https://chrome.google.com/webstore/devconsole/[Chrome Web Store developer dashboard]
.. Update the package
.. Publish the new version
. Connect to the https://addons.mozilla.org/fr/developers/addons[Firefox Add-ons developer dashboard]
.. Update the package
.. Publish the new version
. Connect to the https://addons.opera.com/developer[Opera Add-ons developer dashboard]
.. Update the package
.. Publish the new version
. Connect to the https://partner.microsoft.com/fr-fr/dashboard/microsoftedge/overview[Microsoft Partner Center]
.. Update the package
.. Publish the new version
