= Hacking
:uri-nodejs: http://nodejs.org
:uri-nvm: https://github.com/creationix/nvm

This guide will give you all the necessary information you need to become a successful code contributor!

== Setup

To build this project, you will need {uri-nodejs}[Node.js] >= 4 and `npm` (we recommend {uri-nvm}[nvm] to manage multiple active Node.js versions).

NOTE: If you feel more comfortable with `yarn`, you can use it as an alternative to `npm`

== Building

. Install all the dependencies
+
 $ npm install

. Build the project 
+
 $ npm run build
+
This command will produce a zip file that can be load in Chrome: [.path]_dist/asciidoctor-browser-extension.zip_

. Run tests
+
 $ npm run test

This project is using a code linter to enforce code consistency. 
To make sure that the code you have contributed, follow the code rules, execute the following command:

 $ npm run lint

== Add-on Linter

Mozilla provides a Node.js package to validate an add-on.
You can install the linter with `npm`:

 $ npm install -g addons-linter

This command will install the package globally, so you can use the linter from any directory on your machine.

After installation, run the linter on the archive produced by `npm run build`:

 $ addons-linter dist/asciidoctor-browser-extension.zip

== Release

. Build and run the tests
. Make sure that everything is working fine by loading an unpack extension
. Edit the `changelog.adoc` file
. Update the version in `app/manifest.json`
. Commit the changes
. Tag the version
. Connect to the https://chrome.google.com/webstore/developer/dashboard[Chrome Web Store developper dashboard] and update the package
. Publish
