= Custom Attributes

Custom Attributes are a string of space-separated `_attribute_=_value_` pairs added to the header of each AsciiDoc page viewed by the extension before it is rendered.

Custom Attributes allow you to use the features of AsciiDoc in documents without having to write them each time, or include a separate file of attribute settings.

For example, to add a left hand TOC to each page viewed, add the following Custom Attribute:

[,txt]
----
toc=left
----

== AsciiDoc Attributes

To learn more about AsciiDoc attributes, visit the
xref:asciidoc:attributes:document-attributes.adoc[]
page of the AsciiDoc manual.

== Setting attribute values

Attributes can be set with and without a value, and unset.
The following table shows examples of setting attributes in AsciiDoc with their Custom Attribute equivalents.

[cols="3*a"]
|===
|Action |AsciiDoc |Custom Attributes example

|Set without a value |`:sectnums:` |`sectnums` 
|Set to a value |`:toc: left` |`toc=left` 
|Unset |`:sectnums!:` |`sectnums!`

|===

== Use cases

Use cases for using Custom attributes.

=== Minimal effort writing

Set the most common AsciiDoc attributes used when writing AsciiDoc documents:

.Custom attributes
[,txt,opts="pre-wrap"]
----
toc=left toclevels=7 icons=font experimental source-highlighter=highlight.js
----

.Equivalent AsciiDoc
[,asciidoc]
----
:toc: left <.>
:toclevels: 7 <.>
:icons: font <.>
:experimental: <.>
:source-highlighter: highlight.js <.>
----
<.> A left hand TOC
<.> TOC shows the maximum of 7 levels if present
<.> Use Font Awesome for icons and admonition icons
<.> Enable GUI macros +
`\btn:[button]` for btn:[button] +
`\kbd:[control-A]` for kbd:[control-A] and +
`\menu:Menu[Item,...]` for select menu:Menu[Item,...]
<.> Syntax highlighting with `highlight.js`

=== Review AsciiDocs without a TOC

Use a TOC to help make reviewing longer AsciiDoc documents easier that don't have a TOC without changing the file.

.Custom attributes
[,txt,opts="pre-wrap"]
----
toc=left toclevels=7
----
