on: workflow_dispatch

name: Submit to Web Stores

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: "dist/asciidoctor-browser-extension-{version}.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
